M48
; DRILL file {KiCad 7.0.2} date Mon 08 May 2023 10:42:51 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-08T22:42:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.350
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.280
%
G90
G05
T1
X65.62Y-90.17
X76.62Y-90.17
T2
X71.77Y-85.47
T4
X71.12Y-90.17
T3
X72.585Y-85.472G85X70.935Y-85.472
G05
T0
M30
